version: 2
updates:
    -   package-ecosystem: nuget
        directory: "/"
        target-branch: "develop"
        schedule:
            interval: "weekly"
    -   package-ecosystem: pnpm
        directory: "/Epsilon.Host.Frontend"
        target-branch: "develop"
        schedule:
            interval: "weekly"
    -   package-ecosystem: docker
        directory: "/"
        target-branch: "develop"
        schedule:
            interval: "weekly"