version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: nuget
    directory: /
    target-branch: main
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /Epsilon.Host.Frontend
    target-branch: main
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /Epsilon.Host.Frontend
    target-branch: main
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /Epsilon.Host.WebApi
    target-branch: main
    schedule:
      interval: monthly
