version: "3.3"
services:
    traefik:
        image: "traefik:v2.10"
        container_name: "Epsilon-Traefik"
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            # HTTPS / Certificates
            - "--certificatesresolvers.letsencrypt.acme.email=typiqally@gmail.com"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "../traefik/letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    frontend:
        container_name: Epsilon-Frontend
        build:
            context: ./Epsilon.Host.Frontend
            dockerfile: ./Dockerfile
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.rule=Host(`epsilon.deltafhict.nl`)"
            - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
            - "traefik.http.routers.whoami.entrypoints=web"

    api:
        container_name: Epsilon-API
        build:
            context: .
            dockerfile: ./Epsilon.Host.WebApi/Dockerfile
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=PathPrefix(`/backend`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.rule=Host(`epsilon.deltafhict.nl`)"
            - "traefik.http.routers.api.tls.certresolver=letsencrypt"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80;
            - LIT__TargetUri=http://+:80;
    db:
        container_name: Epsilon-DB
        image: mariadb:10
        environment:
            MARIADB_ROOT_PASSWORD: not_toor
            MARIADB_DATABASE: epsilon
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql:/data
