services:
  api:
    container_name: Epsilon-API
    build:
      context: .
      dockerfile: ./Epsilon.Host.WebApi/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
  frontend:
    container_name: Epsilon-Frontend
    build:
      context: ./Epsilon.Host.Frontend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  db:
    container_name: Epsilon-DB
    image: mariadb:10
    environment:
        MARIADB_ROOT_PASSWORD: not_toor
        MARIADB_DATABASE: epsilon
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/data